[workspace]
# Enable Git releases, changelog updates, and crates.io publishing
git_release_enable = true
git_tag_enable = true
changelog_update = true

[[package]]
name = "tempo-cli"
# Allow any version changes
semver_check = false
# Enable releases for this package including crates.io publishing
release = true
# Enable publishing to crates.io
publish = true
