[workspace]
# Enable Git releases and changelog updates
git_release_enable = true
git_tag_enable = true
changelog_update = true

[[package]]
name = "tempo-cli"
# Allow any version changes
semver_check = false
# Enable releases for this package
release = true
